services:
    php:
        build:
            context: docker/php
            target: default
        volumes:
            - .:/var/www/html
            - assets:/var/www/html/web/assets
            - data:/var/www/html/data
            - cache:/var/www/.cache
        env_file:
            - ./docker/php/env
            - ./docker/postgres/env
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - wallabag-net
            - proxy-net

    postgres:
        image: postgres:11-alpine
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file:
            - ./docker/postgres/env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U wallabag -q || exit 1"]
            interval: 10s
            timeout: 3s
            retries: 3
        networks:
            - wallabag-net

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "15672:15672"
        env_file:
            - ./docker/rabbitmq/env
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - wallabag-net

    redis:
        image: redis:6-alpine
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 3s
            retries: 3
        networks:
            - wallabag-net

volumes:
    db-data:
        driver: local
    assets:
        driver: local
    data:
        driver: local
    cache:
        driver: local

networks:
  wallabag-net:
    driver: bridge
  proxy-net:
    external: true
